### ISSUE TITLE
logproxy as FAAS

### ISSUE THREAD

**Issue by bimalkm191-philips** [philips-software/logproxy#165]
I am moving my issue to official github 

Can we get a FAAS which will be easier to use instead of doing all the below setup for iron.io?

1. Configure logproxy
2. Get the code docker pull philipssoftware/logproxy
3. Create a new micro service using the keys and binding to log proxy service
4. Do we need a rabitmq service also?
5. Cf push the micro service which will enable iron.io logs to push to Kibana
6. Need help how iron.io config will use the proxy service?

**Comment by loafoe** [comment]
hi @bimalkm191-philips , siderite will include optional direct logging support to HSDP.  There will be no need to use logproxy at all. It will use the same underlying logging mechanism as logproxy but baked directly into siderite itself. 

Progress on that feature can be tracked here: https://github.com/philips-labs/siderite/issues/16

The reason for this choice of solution is to be independent of the iron.io logging capture method as siderite can then offer the same logging capability when running on backends like [ferrite](https://github.com/philips-labs/ferrite)

closing this issue.
