### ISSUE TITLE
Improve Integration Tests

### ISSUE THREAD

**Issue by krmeda** [philips-software/logproxy#2]
- [x] Add Integration Tests (Support a HTTP Mock scenario by default with option to send to a real endpoint)
- [x] Link to pipeline
- [ ] Performance Tests

**Comment by loafoe** [comment]
@krmeda are you referring to full end to end performance tests?

**Comment by krmeda** [comment]
Yes.. i was referring to that... similar to how [HSDP Logging KPI](https://www.hsdp.io/documentation/logging/references/key-performance-indicators) is documented.
