### ISSUE TITLE
introduce on/off flag for "pure passthrough" for base64 encoded logmessages

### ISSUE THREAD

**Issue by rostbel** [philips-software/logproxy#245]
Starting LogProxy v1.6x the "pure passthrough" functionality was introduced allowing LogEvent.logData.message encoded in base64 to be passed unaltered to Kibana. In versions prior to v1.6x LogProxy would encode clear text into base64 automatically.

Recently Kibana experiencing long downtimes which drives us to inspect log messages from services using CF and makes it a huge hassle to decode each message manually.

It would be nice to have an on/off switch for "pure passthrough"  functionality on TF level or even better to have LogProxy automatically recognize the clear text vs base64encoded and handle it accordingly.

Will appreciate any help on the matter! @loafoe

**Comment by loafoe** [comment]
@rostbel `v1.7.3` introduces some logic to automatically encode the `message` field in case it is not encoded in "pure passthrough" mode. This should implement the behaviour you are looking for without needing any special config
