### ISSUE TITLE
Update docker base image to latest version

### ISSUE THREAD

**Issue by sailinder** [philips-software/logproxy#385]
For our product (PICS / Cardiology Reporting) we are updating all base images to have the latest/best image with the latest security fixes.
Can we update the docker base image 
FROM golang:1.20.1-alpine to golang:1.21.6-alpine or golang:1.21.6-alpine3.19?

**Comment by loafoe** [comment]
Updated in release `v1.9.0`

**Comment by sailinder** [comment]
Thank you!
