### ISSUE TITLE
Support Datadog APM tracing

### ISSUE THREAD

**Issue by krmeda** [philips-software/logproxy#53]
As a System Operator using logproxy to drain logs
I want to monitor my running logproxy instances using Datadog APM
so that I can monitor, trend and respond to issues occurring in my environment.

Refer to https://docs.datadoghq.com/tracing/setup/go/ for information on how to integrate tracing.

**Comment by loafoe** [comment]
@krmeda adding Elastic APM support to begin with: #89

**Comment by loafoe** [comment]
We will go with OpenTracing
